import csv
import json
import re
import sys


def clean_quote(quote):
    """Clean up the quote text by removing extra whitespace and normalizing punctuation."""
    # Replace multiple spaces with a single space
    quote = re.sub(r"\s+", " ", quote.strip())
    return quote


def convert_json_to_csv(input_file, output_file):
    """Convert Fancy Nancy quotes JSON file to CSV format for Supabase import."""
    try:
        # Read the JSON file
        with open(input_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Create CSV file
        with open(output_file, "w", encoding="utf-8", newline="") as f:
            # Define CSV writer with the required fields for your table
            csv_writer = csv.writer(f)

            # Write header row (id field will be auto-generated by Supabase)
            csv_writer.writerow(["quote", "url"])

            # Process each quote
            for item in data:
                quote = clean_quote(item["saying"])
                url = item["post_url"]

                # Write the row to CSV
                csv_writer.writerow([quote, url])

        print(f"Successfully converted {len(data)} quotes to CSV format.")
        print(f"CSV file saved as: {output_file}")

    except Exception as e:
        print(f"Error: {str(e)}")
        return False

    return True


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python convert_quotes.py input.json output.csv")
    else:
        input_file = sys.argv[1]
        output_file = sys.argv[2]
        convert_json_to_csv(input_file, output_file)
